config/routes.rb
Rails.application.routes.draw do

   devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks',
    registrations: "users/registrations"
  }
  mount Attachinary::Engine => "/attachinary"
  root to: "pages#partner", constraints: lambda { |r| r.env["warden"].authenticate? && r.env["warden"].user.status == true }
  root to: "pages#dashboard", constraints: lambda { |r| r.env["warden"].authenticate? }
  root to: 'pages#home'
  get '/users/:id', to: "users#summary", as: "user_summary"
  get "/dashboard/", to: "pages#dashboard"
  get "/dashboard/edit-skills", to: "pages#edit_skills"
  patch "/dashboard/update-skills", to: "pages#update_skills"
  put "/dashboard/update-skills", to: "pages#update_skills"
  get "/partner/", to: "pages#partner"
  patch "/connections/:connection_id/meetings/:id/review", to: "meetings#change_review", as: "review"
  put "/connections/:connection_id/meetings/:id/review", to: "meetings#change_review"
  delete "/connections/:connection_id/meetings/:id/review", to: "meetings#destroy_review"
  get "/connections/:connection_id/meetings/:id/edit-review", to: "meetings#edit_review", as: "edit_review"
  patch "/connections/:connection_id/meetings/:id/status/", to: "connections#finalize_status", as: "status"
  put "/connections/:id/status/", to: "connections#finalize-status"
  patch "/connections/:id/cancel/" ,to: "connections#cancel", as: "cancel_connection"
  put "/connections/:id/cancel/" ,to: "connections#cancel"
  patch "/connections/:id/decline/" ,to: "connections#decline", as: "decline_connection"
  put "/connections/:id/decline/" ,to: "connections#decline"
  resources :recommended_users, only: [:index, :create, :update, :destroy]
  resources :categories, only: [:index]
  resources :skills, only: [:index]
  resources :user_skills, only: [:create, :destroy]
  resources :places do
    resources :availabilities, only: [:index, :create, :edit, :update, :destroy]
  end
  resources :connections, only: [:index, :create, :update, :show] do
    resources :meetings, only: [:create, :show, :update] do
      resources :places, only: [:index, :show, :update]
      resources :messages, only: [:create]
    end
  end

end

app/models/meeting.rb
class Meeting < ApplicationRecord
  belongs_to :connection
  belongs_to :place
  has_many :messages

  validates :connection, presence: true

end

app/controllers/meetings_controller.rb
class MeetingsController < ApplicationController
  before_action :find_connection_meeting, only: [ :show, :change_review, :edit_review, :destroy_review ]

  def index
    @meetings = Meeting.all
  end

  def create
  end

  def update
  end

  def show
    @messages = @meeting.messages
    @new_message = Message.new
    if @connection.guest == current_user
      @other_meeter = @connection.host
      @current_review = @meeting.guest_review
      @other_review = @meeting.host_review
    else
      @other_meeter = @connection.guest
      @current_review = @meeting.host_review
      @other_review = @meeting.guest_review
    end
  end

  def change_review
    if @meeting.update(review_params)
      redirect_to connection_meeting_path(@connection, @meeting)
    else
      render :edit
    end
  end

  def edit_review
  end

  def destroy_review
    if @connection.guest == current_user
      @meeting.guest_review = nil
    else
      @meeting.host_review = nil
    end
    @meeting.save
    redirect_to connection_meeting_path(@connection, @meeting)
  end

  private

  def review_params
    params.require(:meeting).permit(:host_review, :guest_review)
  end

  def find_connection_meeting
    @meeting = Meeting.find(params[:id])
    @connection = @meeting.connection
  end
end

app/helpers/meetings_helper.rb
module MeetingsHelper
end

app/views/meetings/_form_finalize_status.html.erb
<%= simple_form_for @connection, url: status_path(@connection, @meeting), method: :patch do |f| %>
  <%= f.input :status, as: :hidden, input_html: { value: local_assigns[:value] } %>
  <%= f.button :submit, value: local_assigns[:text], class: "togather-button btn-blue" %>
<% end %>

app/views/meetings/_form_review.html.erb
<div>
  <%= simple_form_for @meeting, url: review_path(@connection, @meeting), method: :patch do |f| %>
    <%= f.error_notification %>
    <% if @connection.guest == current_user %>
      <%= f.input :guest_review %>
    <% else %>
      <%= f.input :host_review %>
    <% end %>
    <%= f.button :submit, value: "submit", class: "togather-button btn-yellow" %>
  <% end %>
</div>

app/views/meetings/_reviews.html.erb
<% if @current_review %>
  <h4> Your review </h4>
  <p><%= @current_review %></p>
  <%= link_to "Edit", edit_review_path(@connection, @meeting), class: "togather-button btn-yellow" %>
  <%= link_to "Delete", review_path(@connection, @meeting), method: :delete, class: "togather-button btn-yellow" %>
<% else %>
  <h2> Make a review </h2>
  <%= render "form_review" %>
<% end %>


<% if @other_review %>
  <h4><%= "#{@other_meeter.first_name} #{@other_meeter.last_name} 's Review" %></h4>
  <p style="font-size: 14px"><%= @other_review %></p>
<% else %>
  <h4><%= "#{@other_meeter.first_name} #{@other_meeter.last_name} n'a pas encore fait de review" %></h4>
<% end %>

app/views/meetings/edit_review.html.erb
<h1>edit review</h1>

<%= render "form_review" %>

app/views/meetings/show.html.erb
<div class="container-fluid">
  <div class="wrapper">
    <div class="row">
      <div class="col-md-3 wrapper-col-3">
      <div class="row">

        <%= render "shared/navbar" %>
        <div class="profil-wrapper">
          <div class="profile-bio">
            <% if @meeting.connection.guest != current_user %>
              <div class="profile-picture">
                <% if @meeting.connection.guest.photo? %>
                  <%= cl_image_tag @meeting.connection.guest.photo.path, gravity: "face", width: 100, height: 100, :crop=>"fill", radius: "max", class: "avatar" %>
                <% else %>
                  <%= image_tag "http://placehold.it/100x100" %>
                <% end %>
              </div>
              <div class="desc-bio">
                <span class="bio-title"><%= @meeting.connection.guest.first_name%> <%=@meeting.connection.guest.last_name %></span>
                <p>
                  <%= truncate(@meeting.connection.guest.bio, length: 100) %>
                </p>
              </div>
              <!-- <h3><%= @meeting.connection.guest.first_name%> <%=@meeting.connection.guest.last_name %></h3> -->
            <% elsif @meeting.connection.host != current_user %>
              <div class="profile-picture">
                <% if @meeting.connection.host.photo? %>
                  <%= cl_image_tag @meeting.connection.host.photo.path, gravity: "face", width: 100, height: 100, :crop=>"fill", radius: "max", class: "avatar" %>
                <% else %>
                  <%= image_tag "http://placehold.it/100x100" %>
                <% end %>
              </div>
              <div class="desc-bio">
                <span class="bio-title"><%= @meeting.connection.host.first_name%> <%=@meeting.connection.host.last_name %></span>
                <p>
                  <%= truncate(@meeting.connection.host.bio, length: 100) %>
                </p>
              </div>
              <!-- <h3><%= @meeting.connection.host.first_name%> <%=@meeting.connection.host.last_name %></h3> -->
            <% end %>
          </div>
          <div class="profile-details">
            <div class="profile-workplace">
              <% if @meeting.connection.guest != current_user %>
                <span class="bio-title"><%= @meeting.connection.guest.first_name %>'s work place</span>
                <p>
                  <% if @meeting.connection.guest.work_place.nil? %>
                    <%= "-" %>
                  <% else %>
                    <%= @meeting.connection.guest.work_place %>
                  <% end %>
                </p>
              <% elsif @meeting.connection.host != current_user %>
                <span class="bio-title"><%= @meeting.connection.host.first_name %>'s work place</span>
                <p>
                  <% if @meeting.connection.host.work_place.nil? %>
                    <%= "-" %>
                  <% else %>
                    <%= @meeting.connection.host.work_place %>
                  <% end %>
                </p>
              <% end %>
            </div>
            <div class="profile-interests">
              <% if @meeting.connection.guest != current_user %>
                <span class="bio-title"><%= @meeting.connection.guest.first_name%>'s interests</span>
                <div class="profile-skills">
                  <div class="skills-icons">
                    <% s = @meeting.connection.guest.skills.shuffle %>
                    <% skills = s.sample(14) %>
                    <% skills.each do |skill| %>
                      <%= image_tag(skill.icon) %>
                    <% end %>
                    ...
                  </div>
                </div>
              <% elsif @meeting.connection.host != current_user %>
                <span class="bio-title"> <%= @meeting.connection.host.first_name%>'s interests</span>
                <div class="profile-skills">
                  <div class="skills-icons">
                    <% s = @meeting.connection.host.skills.shuffle %>
                    <% skills = s.sample(14) %>
                    <% skills.each do |skill| %>
                      <%= image_tag(skill.icon) %>
                    <% end %>
                    ...
                  </div>
                </div>
              <% end %>
            </div>
          </div>
        <hr>


          <div class="choice-review">
            <% if @meeting.date && @meeting.date < DateTime.now %>
              <% if @meeting.connection.status != "connected" %>
                <% if @meeting.connection.host != current_user %>
                  <h5> Do you want to share your network with <%=@meeting.connection.host.first_name%> ? </h5>
                <% else %>
                  <h5> Do you want to share your network with <%= @meeting.connection.guest.first_name%> ? </h5>
                <% end %>
                <div style="text-align: center;">
                  <span>
                    <%= render "form_finalize_status", text: "Connect our Networks", value: "connected" %>
                  </span>
                  <span>
                    <%= render "form_finalize_status", text: "Refuse it", value: "refused" %>
                  </span>
                </div>
              <% else %>
                <% if @meeting.connection.host != current_user %>
                  <h5> You are connected with <%=@meeting.connection.host.first_name%> </h5>
                <% else %>
                  <h5> You are connected with <%= @meeting.connection.guest.first_name%> </h5>
                <% end %>
                <%= render "form_finalize_status", text: "Refuse it", value: "refused" %>
              <% end %>
            <% end %>
          </div>
        </div>
      </div>
      </div>

      <div class="col-md-9 wrapper-col-9">



        <div class="wrapping-case" style="padding: 0 30px;">
          <div class="row">
            <div class="col-md-7">
              <div class="messagerie">
                <div class="suggestion-wrapper">
                  <div class="suggestion-content" >
                    <h3 id="hiding-bar">
                      Messages
                    </h3>
                    <div class="underspace"></div>
                    <%= render 'shared/message_row' %>

                  </div>
                </div>
              </div>
            </div>
            <div class="col-md-5">
              <h1>Our Meeting</h1>
              <p class="text-muted">
                <% if @meeting.place %>
                  <%= @meeting.place.name %> - <%= @meeting.date.strftime('%m/%d/%Y %I:%M %p') %>
                  <br>
                  <br>
                  <%= link_to "Choose another place", connection_meeting_places_path(@connection, @meeting), class: "togather-button btn-yellow"  %>
                <% else %>
                  <%= link_to "Choose a place", connection_meeting_places_path(@connection, @meeting), class: "togather-button btn-yellow" %>
                <% end %>
              </p>
              <% if @meeting.date && @meeting.date < DateTime.now %>
                <h3> Add a review to your meeting</h3>
                <%= render 'reviews' %>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>