config/routes.rb
Rails.application.routes.draw do

   devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks',
    registrations: "users/registrations"
  }
  mount Attachinary::Engine => "/attachinary"
  root to: "pages#partner", constraints: lambda { |r| r.env["warden"].authenticate? && r.env["warden"].user.status == true }
  root to: "pages#dashboard", constraints: lambda { |r| r.env["warden"].authenticate? }
  root to: 'pages#home'
  get '/users/:id', to: "users#summary", as: "user_summary"
  get "/dashboard/", to: "pages#dashboard"
  get "/dashboard/edit-skills", to: "pages#edit_skills"
  patch "/dashboard/update-skills", to: "pages#update_skills"
  put "/dashboard/update-skills", to: "pages#update_skills"
  get "/partner/", to: "pages#partner"
  patch "/connections/:connection_id/meetings/:id/review", to: "meetings#change_review", as: "review"
  put "/connections/:connection_id/meetings/:id/review", to: "meetings#change_review"
  delete "/connections/:connection_id/meetings/:id/review", to: "meetings#destroy_review"
  get "/connections/:connection_id/meetings/:id/edit-review", to: "meetings#edit_review", as: "edit_review"
  patch "/connections/:connection_id/meetings/:id/status/", to: "connections#finalize_status", as: "status"
  put "/connections/:id/status/", to: "connections#finalize-status"
  patch "/connections/:id/cancel/" ,to: "connections#cancel", as: "cancel_connection"
  put "/connections/:id/cancel/" ,to: "connections#cancel"
  patch "/connections/:id/decline/" ,to: "connections#decline", as: "decline_connection"
  put "/connections/:id/decline/" ,to: "connections#decline"
  resources :recommended_users, only: [:index, :create, :update, :destroy]
  resources :categories, only: [:index]
  resources :skills, only: [:index]
  resources :user_skills, only: [:create, :destroy]
  resources :places do
    resources :availabilities, only: [:index, :create, :edit, :update, :destroy]
  end
  resources :connections, only: [:index, :create, :update, :show] do
    resources :meetings, only: [:create, :show, :update] do
      resources :places, only: [:index, :show, :update]
      resources :messages, only: [:create]
    end
  end

end

app/models/category.rb
class Category < ApplicationRecord
  has_many :skills
  has_many :user_skills, through: :skills
  has_many :users, through: :user_skills
  validates :name, presence: true
  has_attachment :photo

  def select_label
    "#{Category.first.name}"
  end

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
    @categories = Category.all
  end

  def categorie_params
    params.require(:product).permit( :name, :photo)
  end

end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_form.html.erb
<div class="cat-form">
  <%= simple_form_for :id_categories, url: skills_path, method: :get do |f| %>
    <%= f.input :categories, collection: @categories, as: :check_boxes, required: true, input_html: { multiple: true } %>
    <%= f.button :submit, value: "submit" %>
  <% end %>
</div>

<div class="category-selection">
  <% Category.all.each do |category| %>
  <div class="category-card unselected" id="<%= category.id %>">
    <%= cl_image_tag category.photo.path, class: "category-img" %>
    <div class="category-title">
      <h3><%= category.name %></h3>
    </div>
    <div class="category-skills-icons">
      <div class="category-skills-sample">
        <div class="carousel slide" data-ride="carousel" data-interval=<%= rand(3000..5000) %> data-pause="null">
          <div class="carousel-inner" role="listbox">
            <div class="item active">
              <div class="inline-icons">
                <% askills = category.skills.sample(3) %>
                <% askills.each do |askill| %>
                  <%= image_tag(askill.icon) %>
                <% end %>
              </div>
            </div>
            <div class="item">
              <div class="inline-icons">
                <% bskills = category.skills.sample(3) %>
                <% bskills.each do |bskill| %>
                  <%= image_tag(bskill.icon) %>
                <% end %>
              </div>
            </div>
            <div class="item">
              <div class="inline-icons">
                <% cskills = category.skills.sample(3) %>
                <% cskills.each do |cskill| %>
                  <%= image_tag(cskill.icon) %>
                <% end %>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <% end %>
</div>
<div class="text-center">
  <div class="submit-wrap">
    <button type="button" class="btn btn-default submit-cat">Submit selection</button>
  </div>
</div>

<% content_for(:after_js) do %>
  <script>
    $(document).ready(function(){
      $('.submit-cat').on('click', function(event){
        $('input:submit').click();
      });
      $('.category-card').on('click', function(event) {
        var val = this.id;
        console.log(val);
        $(this).toggleClass('active-card');
        $(this).toggleClass('unselected');
        $('input:checkbox[value='+val+']').click();
        // $('input:checkbox').prop('checked', !('input:checkbox').prop('checked'));
      });
    });
  </script>
<% end %>

app/views/categories/index.html.erb
<div class="container">
  <div class="row">
    <h1>Choose your interests</h1>
    <p>Choose at least one category you are interested in.</p>
    <%= render "form" %>
  </div>
</div>