config/routes.rb
Rails.application.routes.draw do

   devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks',
    registrations: "users/registrations"
  }
  mount Attachinary::Engine => "/attachinary"
  root to: "pages#partner", constraints: lambda { |r| r.env["warden"].authenticate? && r.env["warden"].user.status == true }
  root to: "pages#dashboard", constraints: lambda { |r| r.env["warden"].authenticate? }
  root to: 'pages#home'
  get '/users/:id', to: "users#summary", as: "user_summary"
  get "/dashboard/", to: "pages#dashboard"
  get "/dashboard/edit-skills", to: "pages#edit_skills"
  patch "/dashboard/update-skills", to: "pages#update_skills"
  put "/dashboard/update-skills", to: "pages#update_skills"
  get "/partner/", to: "pages#partner"
  patch "/connections/:connection_id/meetings/:id/review", to: "meetings#change_review", as: "review"
  put "/connections/:connection_id/meetings/:id/review", to: "meetings#change_review"
  delete "/connections/:connection_id/meetings/:id/review", to: "meetings#destroy_review"
  get "/connections/:connection_id/meetings/:id/edit-review", to: "meetings#edit_review", as: "edit_review"
  patch "/connections/:connection_id/meetings/:id/status/", to: "connections#finalize_status", as: "status"
  put "/connections/:id/status/", to: "connections#finalize-status"
  patch "/connections/:id/cancel/" ,to: "connections#cancel", as: "cancel_connection"
  put "/connections/:id/cancel/" ,to: "connections#cancel"
  patch "/connections/:id/decline/" ,to: "connections#decline", as: "decline_connection"
  put "/connections/:id/decline/" ,to: "connections#decline"
  resources :recommended_users, only: [:index, :create, :update, :destroy]
  resources :categories, only: [:index]
  resources :skills, only: [:index]
  resources :user_skills, only: [:create, :destroy]
  resources :places do
    resources :availabilities, only: [:index, :create, :edit, :update, :destroy]
  end
  resources :connections, only: [:index, :create, :update, :show] do
    resources :meetings, only: [:create, :show, :update] do
      resources :places, only: [:index, :show, :update]
      resources :messages, only: [:create]
    end
  end

end

app/models/availability.rb
class Availability < ApplicationRecord
  belongs_to :place
  validates :min_day, presence: true
  validates :max_day, presence: true
  validates :min_time, presence: true
  validates :max_time, presence: true
  # faire que la date de fin et plus grande que la date de début

  # def self.convert_str_to_dates(params)
  #   str_date = "#{params[:min_day][0..2]}, 01 Jan 2001 "
  #   str_hour = "#{params[:min_hour]}:#{params[:min_minute]}:00 GMT"
  #   min_date = DateTime.httpdate(str_date + str_hour)

  #   str_date = "#{params[:max_day][0..2]}, 01 Jan 2001 "
  #   str_hour = "#{params[:max_hour]}:#{params[:max_minute]}:00 GMT"
  #   max_date = DateTime.httpdate(str_date + str_hour)
  #   {min_date: min_date, max_date: max_date}
  # end

end

app/controllers/availabilities_controller.rb
class AvailabilitiesController < ApplicationController
  before_action :defind_arrays, only: [ :index, :create, :edit, :update ]
  before_action :find_availability, only: [ :edit, :update, :destroy ]
  before_action :save_availability, only: [ :create, :update ]

  def index
  end

  def create
    if valid_form?
      redirect_to place_availabilities_path(@place)
    else
      render :index
    end
  end

  def edit
  end

  def update
    if valid_form?
      redirect_to place_availabilities_path(@place)
    else
      render :edit
    end
  end

  def destroy
    @availability.destroy
    redirect_to place_availabilities_path(@availability.place, @availability )
  end

  private

  def new_date_params
    params.require(:new_date).permit!
  end

  def defind_arrays
    @place = Place.find(params[:place_id])
    @days = ["Monday", "Tuesday", "Wenesday", "Thursday", "Friday", "Saturday", "Sunday"]
    @hours = ["00", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23"]
    @minutes = ["00", "10", "20", "30", "40", "50"]
  end

  def find_availability
    @availability = Availability.find(params[:id])
  end

  def save_availability
    @p = new_date_params
    @max_time = Time.utc(2000, 1, 1, @p[:max_hour].to_i, @p[:max_minute].to_i )
    @min_time = Time.utc(2000, 1, 1, @p[:min_hour].to_i, @p[:min_minute].to_i )
    @availability = @place.availabilities.new(  max_day: @p[:max_day],
                                                min_day: @p[:min_day],
                                                max_time: @max_time,
                                                min_time: @min_time)
  end

  def valid_form?
    @days.index(@p[:max_day]) >= @days.index(@p[:min_day]) && @max_time > @min_time && @availability.save
  end
end

app/helpers/availabilities_helper.rb
module AvailabilitiesHelper
end

app/views/availabilities/_form.html.erb
<div class="container">
  <div>
    <%= simple_form_for :new_date, url: place_availabilities_path(@place), method: :post do |f| %>
      <%= f.error_notification %>
      <%= f.input :min_day, collection: @days, selected: "Monday" %>
      <%= f.input :max_day, collection: @days, selected: "Sunday" %>
      <%= f.input :min_hour, collection: @hours, selected: "00" %>
      <%= f.input :min_minute, collection: @minutes, selected: "00" %>
      <%= f.input :max_hour, collection: @hours, selected: "00" %>
      <%= f.input :max_minute, collection: @minutes, selected: "00" %>
      <%= f.button :submit, value: "submit" %>
    <% end %>
  </div>
</div>

app/views/availabilities/_form_edit.html.erb
<div class="container">
  <div>
    <%= simple_form_for :new_date, url: place_availabilities_path(@place), method: :post do |f| %>
      <%= f.error_notification %>
      <%= f.input :min_day, collection: @days, selected: @availability.min_day %>
      <%= f.input :max_day, collection: @days, selected: @availability.max_day %>
      <%= f.input :min_hour, collection: @hours, selected: "#{@availability.min_time.strftime "%H"}" %>
      <%= f.input :min_minute, collection: @minutes, selected: "#{@availability.min_time.strftime "%M"}" %>
      <%= f.input :max_hour, collection: @hours, selected: "#{@availability.max_time.strftime "%H"}" %>
      <%= f.input :max_minute, collection: @minutes, selected: "#{@availability.max_time.strftime "%M"}" %>
      <%= f.button :submit, value: "submit" %>
    <% end %>
  </div>
</div>

app/views/availabilities/edit.html.erb
<div class="monbackground">
<div class="container">

  <div class="text-center">
    <h1> Edit my availabilities</h1>
  </div>

  <%= render "form_edit" %>

</div>
</div>

app/views/availabilities/index.html.erb
<div class="container">

  <div class="text-center">
    <h1> Choose dates </h1>
  </div>

  <% if @place.availabilities.first %>
    <ul>
    <% @place.availabilities.each do |availability| %>
      <% if availability.id %>
        <li>
          <%= "#{availability.min_day} - #{availability.max_day} : " %>
          <%= "#{availability.min_time.strftime "%Hh%M"} - #{availability.max_time.strftime "%Hh%M"}" %>
          <%= link_to "Edit", edit_place_availability_path(@place, availability) %>
          <%= link_to "Destroy", place_availability_path(@place, availability), method: :delete %>
        </li>
      <% end %>
    <% end %>
    </ul>
  <% end %>

  <%= render "form" %>
  <p><%= link_to "Return on show place", place_path(@place) %></p>


</div>