config/routes.rb
Rails.application.routes.draw do

   devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks',
    registrations: "users/registrations"
  }
  mount Attachinary::Engine => "/attachinary"
  root to: "pages#partner", constraints: lambda { |r| r.env["warden"].authenticate? && r.env["warden"].user.status == true }
  root to: "pages#dashboard", constraints: lambda { |r| r.env["warden"].authenticate? }
  root to: 'pages#home'
  get '/users/:id', to: "users#summary", as: "user_summary"
  get "/dashboard/", to: "pages#dashboard"
  get "/dashboard/edit-skills", to: "pages#edit_skills"
  patch "/dashboard/update-skills", to: "pages#update_skills"
  put "/dashboard/update-skills", to: "pages#update_skills"
  get "/partner/", to: "pages#partner"
  patch "/connections/:connection_id/meetings/:id/review", to: "meetings#change_review", as: "review"
  put "/connections/:connection_id/meetings/:id/review", to: "meetings#change_review"
  delete "/connections/:connection_id/meetings/:id/review", to: "meetings#destroy_review"
  get "/connections/:connection_id/meetings/:id/edit-review", to: "meetings#edit_review", as: "edit_review"
  patch "/connections/:connection_id/meetings/:id/status/", to: "connections#finalize_status", as: "status"
  put "/connections/:id/status/", to: "connections#finalize-status"
  patch "/connections/:id/cancel/" ,to: "connections#cancel", as: "cancel_connection"
  put "/connections/:id/cancel/" ,to: "connections#cancel"
  patch "/connections/:id/decline/" ,to: "connections#decline", as: "decline_connection"
  put "/connections/:id/decline/" ,to: "connections#decline"
  resources :recommended_users, only: [:index, :create, :update, :destroy]
  resources :categories, only: [:index]
  resources :skills, only: [:index]
  resources :user_skills, only: [:create, :destroy]
  resources :places do
    resources :availabilities, only: [:index, :create, :edit, :update, :destroy]
  end
  resources :connections, only: [:index, :create, :update, :show] do
    resources :meetings, only: [:create, :show, :update] do
      resources :places, only: [:index, :show, :update]
      resources :messages, only: [:create]
    end
  end

end

app/models/place.rb
class Place < ApplicationRecord
  geocoded_by :address
  after_validation :geocode, if: :address_changed?

  belongs_to :user
  has_many :meetings
  has_many :availabilities
  has_attachment :photo, accept: [:jpg, :png]


  validates :name, presence: true
  validates :address, presence: true
  validates :address, uniqueness: true
  validates :description, presence: true
  validates :phone_number, presence: true
  validates :phone_number, uniqueness: true
  validates :type_partner, presence: true

  def order_dates_by_days
    days = ["Monday", "Tuesday", "Wenesday", "Thursday", "Friday", "Saturday", "Sunday"]
    order_dates = {}
    days.each { |day| order_dates[day] = [] }
    self.availabilities.each do |a|
      days[days.index(a.min_day)..days.index(a.max_day)].each do |day|
        order_dates[day] << { min_time: a.min_time, max_time: a.max_time }
      end
    end
    order_dates.each { |day, arr| order_dates[day] = arr.sort_by { |hours| hours[:min_time] } }
    order_dates
  end

  def available?(date)
    days = ["Monday", "Tuesday", "Wenesday", "Thursday", "Friday", "Saturday", "Sunday"]
    availanilities = self.order_dates_by_days
    t = DateTime.strptime(date.strftime("%I:%M%p"), '%I:%M %p')
    day = days[date.wday - 1]
    availanilities[day].each do |a|
      t_min = DateTime.strptime(a[:min_time].strftime("%I:%M%p"), '%I:%M %p')
      t_max = DateTime.strptime(a[:max_time].strftime("%I:%M%p"), '%I:%M %p')
      if t >= t_min && t <= t_max
        return true
      end
    end
    false
  end
end

app/controllers/places_controller.rb
class PlacesController < ApplicationController
  before_action :find_place, only: [ :show, :edit, :update, :destroy ]
  before_action :find_geocoder, only: [ :show, :update ]
  before_action :find_connection_meeting, only: [ :index, :show, :update ]
  before_action :find_availabilities, only: [ :show, :update ]

  def index
    @types = ["Afterwork", "Café", "Lunch snack", "Salad bar", "Restaurant"]
    @places = Place.all
  end

  def new
    @place = Place.new
  end

  def show
  end

  def edit
  end

  def create
    @place = current_user.places.new(place_params)
    if @place.save
      #PlaceMailer.creation_confirmation(@place).deliver_now
      redirect_to place_availabilities_path(@place)
    else
      render :new
    end
  end

  def update
    if current_user.status
      if @place.update(place_params)
        redirect_to partner_path(@user)
      else
        render :edit
      end
    else
      @meeting.place = @place
      if resa_params[:date] != "" && @place.available?(str_to_date(resa_params[:date]))
        @meeting.date = str_to_date(resa_params[:date])
        @meeting.save
        redirect_to connection_meeting_path(@connection, @meeting)
      else
        render :show
      end
    end
  end

  def destroy
    @place.destroy
    redirect_to partner_path(@user)
  end

  private

  def hash_geocoder(place_model)
    Gmaps4rails.build_markers(place_model) do |place, marker|
      marker.lat place.latitude
      marker.lng place.longitude
      marker.infowindow render_to_string(partial: "/places/map_box_place", locals: { place: place })
    end
  end

  def place_params
    params.require(:place).permit(:name, :address, :description, :phone_number, :type_partner, :pax, :photo )
  end

  def resa_params
    params.permit!
  end

  def str_to_date(date)
    DateTime.strptime(date, '%m/%d/%Y %I:%M %p')
  end

  def find_place
    @place = Place.find(params[:id])
  end

  def find_geocoder
    @hash = hash_geocoder(@place)
  end

  def find_connection_meeting
    unless current_user.status
      @connection = Connection.find(params[:connection_id])
      @meeting = Meeting.find(params[:meeting_id])
    end
  end

  def find_availabilities
    @availabilities = @place.order_dates_by_days
  end
end

app/helpers/places_helper.rb
module PlacesHelper
end

app/views/places/_gmaps.html.erb
<script>
  $(document).ready(function() {
    // var styles = [{"featureType":"all","elementType":"all","stylers":[{"lightness":"42"},{"visibility":"on"},{"hue":"#ff0000"},{"saturation":"-100"},{"gamma":"0.78"},{"weight":"0.37"},{"invert_lightness":true}]},{"featureType":"administrative","elementType":"labels.text.fill","stylers":[{"color":"#444444"}]},{"featureType":"landscape","elementType":"all","stylers":[{"color":"#f2f2f2"}]},{"featureType":"poi","elementType":"all","stylers":[{"visibility":"off"}]},{"featureType":"road","elementType":"all","stylers":[{"saturation":-100},{"lightness":45}]},{"featureType":"road.highway","elementType":"all","stylers":[{"visibility":"simplified"}]},{"featureType":"road.arterial","elementType":"labels.icon","stylers":[{"visibility":"off"}]},{"featureType":"transit","elementType":"all","stylers":[{"visibility":"off"}]},{"featureType":"water","elementType":"all","stylers":[{"color":"#3ec7c9"},{"visibility":"on"}]}];

    var handler = Gmaps.build('Google');
    handler.buildMap({
      // provider: {
      //   styles: styles
      // },
      internal: {
        id: 'map' }
      },
      function() {
        markers = handler.addMarkers(<%= hash %>);
        handler.bounds.extendWith(markers);
        handler.fitMapToBounds();
        if (markers.length == 0) {
          handler.getMap().setZoom(2);
        } else if (markers.length == 1) {
          handler.getMap().setZoom(14);
        }
      }
    );
  });
</script>

app/views/places/_map_box.html.erb
<h3>
  <%= link_to place.name, place %>
</h3>
<img src="" alt="">

<p>
  <%= place.type_partner %>
</p>
<p>
  <%= place.description %>
</p>

app/views/places/_map_box_place.html.erb
<h4>
  <%= place.name %>
</h4>
<%= cl_image_tag place.photo.path, width: 200, height: 100, :crop=>"thumb" %>

<p>
  <%= place.type_partner %>
</p>
<p>
  <%= place.description %>
</p>

app/views/places/_options_meeter.html.erb
<div class="form-date-resa">
  <%= simple_form_for :resa, url: connection_meeting_place_path(@connection, @meeting, @place), method: :patch do |f| %>
    <div class="form-inline">
      <div class="form-group">
        <div class='input-group date' id='datetimepicker1'>
          <input type='text' name="date" class="form-control" />
          <span class="input-group-addon">
            <span class="glyphicon glyphicon-calendar"></span>
          </span>
        </div>
        <%= f.button :submit, value: "Book", class: "togather-button btn-yellow" %>
      </div>
    </div>
  <% end %>
</div>
<br>
<div class="monbtnplace">
  <%= link_to "Back", connection_meeting_places_path(@connection, @meeting), class: "togather-button btn-yellow" %>
</div>




<% content_for :after_js do %>
<script type="text/javascript">
  $(function () {
    $('#datetimepicker1').datetimepicker();
    });
</script>
<% end %>

app/views/places/destroy.html.erb
<h1>Places#destroy</h1>
<p>Find me in app/views/places/destroy.html.erb</p>

app/views/places/edit.html.erb
<div class="editbackground">
  <div class="container">

    <div class="text-center">
      <h1>Edit place</h1>
    </div>

      <%= render 'shared/placeform' %>
        <button type="button" class="monbtn">
          <p><%= link_to "Return on show place", place_path(@place) %></p>
        </button>
        </br>


</div>
</div>

app/views/places/index.html.erb
<div id= "#movefromright">
<div class="monbackground">
<div class="container">
  <div class="row">
    <h1 class="montitre">
      Pick a place
    </h1>
  </div>
  <% @types.each do |type| %>
    <div class="row">
      <div class="marow">
        <h2><%= type %> :</h2>

        <% @places.where(type_partner: type).each do |place| %>
          <div class="col-sm-4">
            <div class="macol">
              <% if current_user.status %>

                <div class="card monimage" style="background-image: linear-gradient(rgba(0,0,0,0.2), rgba(0,0,0,0.1)), url(<%= cl_image_path(place.photo.public_id) %>);">
                  <div class="card-description">
                    <h2><%= place.name %></h2>
                    <p><%= place.description %></p>
                  </div>
                  <%= link_to "", place_path(place), class: "card-link" %>
                </div>

              <% else %>

                <div class="card monimage" style="background-image: linear-gradient(rgba(0,0,0,0.2), rgba(0,0,0,0.1)), url(<%= cl_image_path(place.photo.public_id) %>);">
                  <div class="card-description">
                    <h2><%= place.name %></h2>
                    <p><%= place.description %></p>
                  </div>
                  <%= link_to "", connection_meeting_place_path(@connection, @meeting, place), class: "card-link" %>
                </div>
              <% end %>
            </div>
          </div>

        <% end %>
</div>
    </div>
   <% end %>
</div>

</div>
</div>

app/views/places/new.html.erb
<div class ="container">
  <h1>New place</h1>

  <%= render 'shared/placeform' %>
  <p><%= link_to "Cancel", places_path %></p>
</div>

app/views/places/show.html.erb
<div class="total-wrap">
  <div class="container-fluid">
    <div class="row">
      <div class="col-md-3">
        <div class="row">
          <%= render "shared/navbar" %>
          </br>
          </br>
          <div class="col-md-12 no-marginlr-col">
            <div class="cardshow">
              <div class="card monimage" style="background-image: linear-gradient(rgba(0,0,0,0.2), rgba(0,0,0,0.1)), url(<%= cl_image_path(@place.photo.public_id) %>);">
              </div>
            </div>
          </div>
          <div class="col-md-12 no-marginlr-col">
            <ul class="myul myulcentre">
              <div class="col-sm-12">
                <li>
                  <i class="fa fa-thumbs-up fa-2x" aria-hidden="true"></i>
                  <p> Visit our <%= @place.type_partner.downcase %></p>
                  <br>
                </li>
                <li>
                  <i class="fa fa-phone fa-2x" aria-hidden="true"></i>
                  <p><strong> Contact us :</strong></p>
                  <p><%= @place.phone_number %></p>
                  <br>
                </li>
                <li>
                  <i class="fa fa-map-marker fa-2x" aria-hidden="true"></i>
                  <p><strong> Find us :</strong></p>
                  <p><%= @place.address %></p>
                  <br>
                </li>
              </div>
            </ul>
          </div> <!-- row fa -->
        </div> <!-- row card -->
      </div> <!-- col 1 (row1)-->

      <div class="col-md-9 wrapper-col-9">
        <div class="row">
          <div class="col-md-6">
            <div class="monplacemendate">
              <div class="text-center">

                <h1><%= @place.name %></h1>
                <p><%= @place.description %></p>

                <h3> Choose a date : </h3>

                <% if @availabilities.first %>
                  <ul>
                    <div class="myul">
                      <% @availabilities.each do |day, array| %>
                        <li>
                          <p>
                            <strong>
                             <%= day+" : " %>
                            </strong>
                            <span>
                              <% array.each_with_index do |availability, i| %>
                                <%= "#{availability[:min_time].strftime "%Hh%M"} - #{availability[:max_time].strftime "%Hh%M"}" %>
                                <% unless i == array.count - 1 %>
                                  <span>
                                    <%= ", " %>
                                  </span>
                                <% end %>
                              <% end %>
                            </span>
                          </p>
                        </li>
                      <% end %>
                    </div>
                  </ul>
                  <br>
                  <br>
                <% end %>
                <% if current_user.status %>
                  <%= link_to "Delete place", place_path(@place), method: :delete, data: { confirm: "Are you sure you want to delete this product?" } %>
                  <%= link_to "Edit place", edit_place_path(@place) %>
                  <%= link_to "Modify availabilities", place_availabilities_path(@place) %>
                  <%= link_to "Back", partner_path %>
                <% else %>
                  <%= render "options_meeter" %>
                <% end %>
              </div>
            </div>
          </div>
          <div class="col-md-6 no-marginlr-col">
            <div class="row">
              <div class="map-work">
                <% @hash.each do |marker| %>
                  <% marker[:picture] = { "url": "#{image_path("place2.png") }", "width":  32, "height": 32 } %>
                <% end %>
                <% @hashcontent = raw @hash.to_json %>
                <div class="show-place-map">
                  <div id="map">
                    <% content_for(:after_js) do %>
                      <%= render partial: 'gmaps', locals: {hash: @hashcontent} %>
                    <% end %>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div> <!--  row 1 -->
  </div>
</div>